apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-tasks-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-tasks-app
  template:
    metadata:
      name: react-tasks-app-pod
      labels:
        app: react-tasks-app
    spec:
      containers:
        - name: react-tasks-app
          image: eswarmaganti/react-tasks-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80