apiVersion: v1
kind: Service
metadata:
  name: react-tasks-app-service
spec:
  type: NodePort
  selector:
    app: react-tasks-app
  ports:
    - nodePort: 30007
      port: 80
      targetPort: 80
  