apiVersion: v1
kind: Service
metadata:
  name: react-tasks-app-service
spec:
  type: LoadBalancer
  selector:
    app: react-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  