---
- name: playbook to deploy the application to dev server
  hosts: all
  gather_facts: true
  tasks:
    - name: pull the changes of git repo
      git:
        repo: https://github.com/eswarmaganti/mern-tasks-app.git
        dest: /opt/SP/mern-tasks-app
    - name: kill existing docker services
      community.docker.docker_compose_v2:
        project_src: /opt/SP/mern-tasks-app
        state: absent
    # - name: Start the docker services using compose file
    #   shell: |
    #     cd /opt/SP/mern-tasks-app
    #     docker compose up -d
    - name: start the docker container services using compose
      community.docker.docker_compose_v2:
          project_src: /opt/SP/mern-tasks-app
      register: output
    - name: debug output
      debug:
        var: output
