---
- name: playbook to deploy the application to dev server
  hosts: all
  gather_facts: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Create the directory to store source code
      file:
        path: /opt/SP
        state: directory
        mode: '0775'
      become: yes
      become_user: root
    - name: Change the permissions to dir
      shell: |
        chown ubuntu: /opt/SP
      become: yes
      become_user: root

    # pulling the latest compose file changes
    - name: pull the changes of git repo
      git:
        repo: https://github.com/eswarmaganti/mern-tasks-app.git
        dest: /opt/SP/mern-tasks-app
    
    # stopping existing docker container services
    - name: kill existing docker services
      community.docker.docker_compose_v2:
        project_src: /opt/SP/mern-tasks-app
        state: absent

    # task to start the docker container services using compose
    - name: start the docker container services using compose
      community.docker.docker_compose_v2:
          project_src: /opt/SP/mern-tasks-app
      register: output

       
    # debugging the output
    - name: debug output
      debug:
        var: output
